name: Sync ALDC Fork

on:
  workflow_dispatch:

  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            repos/Dynapro-AS/Dynapro.ALDC/merge-upstream \
            -f branch='main'